#!/usr/bin/env node
// Turns the chronicle into the Progress chapter of the settings page: a few captures per
// day downscaled into public/progress/, and a typed data module the page imports. Reads
// docs/chronicle/*; writes only public/progress/ and src/data/buildLog.ts.
//   node scripts/chronicle.mjs && node scripts/build-log.mjs
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const REPO = resolve(process.cwd())
const CHRON = join(REPO, 'docs/chronicle')
const OUT_IMG = join(REPO, 'public/progress')
const OUT_TS = join(REPO, 'src/data/buildLog.ts')
const SHOTS_PER_DAY = 4
const SHOT_WIDTH = 960 // 1440-wide captures downscaled; ~90KB each as JPEG instead of ~500KB PNG

const read = (f) => JSON.parse(readFileSync(join(CHRON, f), 'utf8'))
const c = read('chronicle.json')
const remarks = read('remarks.json')
const milestones = existsSync(join(CHRON, 'milestones.json')) ? read('milestones.json').milestones : []
const viewOrder = existsSync(join(CHRON, 'views.json')) ? read('views.json').views.map((v) => v.name) : []
const git = (...a) => execFileSync('git', a, { cwd: REPO }).toString()

/** Rows in DECISIONS.md at the end of a day: the decision log's own count, read from history. */
function decisionsAt(day) {
  const hash = git('log', '--branches', '--format=%H', '-1', `--until=${day} 23:59:59`, '--', 'docs/DECISIONS.md').trim()
  if (!hash) return 0
  try { return (git('show', `${hash}:docs/DECISIONS.md`).match(/^\| *\d+ *\|/gm) ?? []).length } catch { return 0 }
}

/** The last capture of each view that day, in views.json order — what the day ended looking like. */
function shotsFor(day) {
  const byView = new Map()
  for (const s of c.screenshots.filter((s) => s.day === day)) byView.set(s.view, s) // ascending, so last wins
  const rank = (v) => { const i = viewOrder.indexOf(v); return i === -1 ? 99 : i }
  return [...byView.values()].sort((a, b) => rank(a.view) - rank(b.view)).slice(0, SHOTS_PER_DAY)
}

mkdirSync(OUT_IMG, { recursive: true })
let converted = 0
function publish(shot) {
  const out = shot.file.replace(/\.png$/, '.jpg')
  const dst = join(OUT_IMG, out)
  if (!existsSync(dst)) {
    // sips ships with macOS; -Z fits the longest side, so 1440×900 becomes 960×600.
    execFileSync('sips', ['-Z', String(SHOT_WIDTH), '-s', 'format', 'jpeg', '-s', 'formatOptions', '82', join(CHRON, 'progress', shot.file), '--out', dst], { stdio: 'ignore' })
    converted++
  }
  return `/progress/${out}`
}

const days = c.byDay.map((d) => {
  const r = remarks[d.day] ?? {}
  return {
    day: d.day,
    commits: d.commits,
    insertions: d.insertions,
    deletions: d.deletions,
    byType: d.byType,
    headline: r.headline ?? `${d.commits} commits`,
    body: r.body ?? '',
    decisions: decisionsAt(d.day),
    shots: shotsFor(d.day).map((s) => ({ view: s.view, at: s.at, src: publish(s) })),
  }
})

const short = (n) => n.replace(/^Claude\s+/, '')
const crew = Object.entries(c.models.commits)
  .filter(([k]) => k !== 'uncredited')
  .map(([name, commits]) => ({ name: short(name), commits, byHand: c.models.attributedByHand?.[name] ?? 0, turns: c.models.turns?.[short(name)] ?? 0 }))
for (const [name, turns] of Object.entries(c.models.turns ?? {})) if (!crew.some((x) => x.name === name)) crew.push({ name, commits: 0, byHand: 0, turns })
crew.sort((a, b) => b.commits - a.commits || b.turns - a.turns)

const log = {
  generatedAt: c.generatedAt,
  span: c.span,
  totals: { ...c.totals, uncredited: c.models.commits.uncredited ?? 0, sessions: c.models.sessions, decisions: days[days.length - 1]?.decisions ?? 0 },
  byType: c.byType,
  crew,
  days,
  milestones,
  remote: c.repo.remote,
}

writeFileSync(OUT_TS, `// Generated by scripts/build-log.mjs from docs/chronicle/ — do not edit by hand.
// Regenerate: node scripts/chronicle.mjs && node scripts/build-log.mjs

export interface BuildShot { view: string; at: string | null; src: string }
export interface BuildDay {
  day: string; commits: number; insertions: number; deletions: number
  byType: Record<string, number>; headline: string; body: string
  /** Rows in docs/DECISIONS.md at the end of the day. */
  decisions: number
  shots: BuildShot[]
}
export interface BuildCrew { name: string; commits: number; byHand: number; turns: number }
export interface BuildMilestone { at: string; hash: string; title: string; body: string }
export interface BuildLog {
  generatedAt: string
  span: { first: string | null; last: string | null }
  totals: { commits: number; days: number; insertions: number; deletions: number; sourceFiles: number; screenshots: number; uncredited: number; sessions: number; decisions: number }
  byType: Record<string, number>
  crew: BuildCrew[]
  days: BuildDay[]
  milestones: BuildMilestone[]
  remote: string | null
}

export const BUILD_LOG: BuildLog = ${JSON.stringify(log, null, 2)}
`)

console.log(`build-log: ${log.totals.commits} commits · ${days.length} days · ${days.reduce((n, d) => n + d.shots.length, 0)} shots (${converted} converted) · ${log.totals.decisions} decisions · ${milestones.length} milestones`)
