// Generated by scripts/build-log.mjs from docs/chronicle/ — do not edit by hand.
// Regenerate: node scripts/chronicle.mjs && node scripts/build-log.mjs

export interface BuildShot { view: string; at: string | null; src: string }
export interface BuildDay {
  day: string; commits: number; insertions: number; deletions: number
  byType: Record<string, number>; headline: string; body: string
  /** Rows in docs/DECISIONS.md at the end of the day. */
  decisions: number
  shots: BuildShot[]
}
export interface BuildCrew { name: string; commits: number; byHand: number; turns: number }
export interface BuildMilestone { at: string; hash: string; title: string; body: string }
export interface BuildLog {
  generatedAt: string
  span: { first: string | null; last: string | null }
  totals: { commits: number; days: number; insertions: number; deletions: number; sourceFiles: number; screenshots: number; uncredited: number; sessions: number; decisions: number }
  byType: Record<string, number>
  crew: BuildCrew[]
  days: BuildDay[]
  milestones: BuildMilestone[]
  remote: string | null
}

export const BUILD_LOG: BuildLog = {
  "generatedAt": "2026-09-09T21:26:30.045Z",
  "span": {
    "first": "2026-09-03T17:06:45-05:00",
    "last": "2026-09-09T14:57:36-05:00"
  },
  "totals": {
    "commits": 223,
    "days": 7,
    "insertions": 25514,
    "deletions": 4725,
    "sourceFiles": 147,
    "screenshots": 162,
    "uncredited": 78,
    "sessions": 5,
    "decisions": 240
  },
  "byType": {
    "other": 54,
    "docs": 12,
    "chore": 1,
    "feat": 50,
    "fix": 12,
    "style": 49,
    "design": 43,
    "ops": 1,
    "copy": 1
  },
  "crew": [
    {
      "name": "Fable 5.1",
      "commits": 129,
      "byHand": 0,
      "turns": 3338
    },
    {
      "name": "Codex",
      "commits": 17,
      "byHand": 16,
      "turns": 0
    },
    {
      "name": "Opus 5",
      "commits": 0,
      "byHand": 0,
      "turns": 820
    }
  ],
  "days": [
    {
      "day": "2026-09-03",
      "commits": 27,
      "insertions": 12956,
      "deletions": 644,
      "byType": {
        "other": 1,
        "docs": 6,
        "chore": 1,
        "feat": 14,
        "fix": 5
      },
      "headline": "Design docs at five, a running board by seven",
      "body": "The brief, layout, flows and architecture spec land first, then a fresh Vite scaffold — earlier patterns ported by hand rather than forked, so reviewers reading package.json find no baggage (decision 14). The whole vertical slice follows in ninety minutes: seeded PRNG and a simulated clock, pure HOS math with boundary tests, fifty drivers with ten planted scenarios, rules and filters as config arrays, the three-pane shell, the Lookout rail, and the route file. Two fixes that night were the interesting ones — limit rules were speaking for drivers who had gone dark, and rank was jostling cards on sub-minute ties. A late pass tore out the left nav for a product bar and stood the route file's stops up on a vertical spine.",
      "decisions": 34,
      "shots": [
        {
          "view": "shift-board",
          "at": "2026-09-03T22:57",
          "src": "/progress/2026-09-03-2257-shift-board.jpg"
        },
        {
          "view": "route-file",
          "at": "2026-09-03T22:57",
          "src": "/progress/2026-09-03-2257-route-file.jpg"
        }
      ]
    },
    {
      "day": "2026-09-04",
      "commits": 40,
      "insertions": 5812,
      "deletions": 1851,
      "byType": {
        "feat": 13,
        "fix": 1,
        "docs": 3,
        "style": 5,
        "design": 18
      },
      "headline": "Lookout gets a face, then a voice",
      "body": "The morning is all co-pilot. The route rail becomes a case file — a vertical, proportional duty timeline with the stops as nodes and the active one following scroll (decision 35, superseding the horizontal ribbon shipped the night before). Lookout gains an illustrated face, a one-line read of the shift, and tabs; by midday those tabs have settled on Chat and Timeline, with recommendations as a sticky bar over the chat and the shift's append-only log beside it. The neutrals get retinted twice — warm to blue-slate, then onto the bento key — on the same argument each time: leave coral and the status bands as the only warmth on the board. Then the header clock stops being a readout and becomes the demo control itself, carrying the scrubber and the explained demo actions. The Lookout bar's recommendation cards are compacted to fit beside the chat, and the reassign picker gets pure, tested candidate ordering and filters.",
      "decisions": 107,
      "shots": [
        {
          "view": "shift-board",
          "at": "2026-09-04T19:29",
          "src": "/progress/2026-09-04-1929-shift-board.jpg"
        },
        {
          "view": "route-file",
          "at": "2026-09-04T19:29",
          "src": "/progress/2026-09-04-1929-route-file.jpg"
        },
        {
          "view": "lookout-timeline",
          "at": "2026-09-04T19:29",
          "src": "/progress/2026-09-04-1929-lookout-timeline.jpg"
        }
      ]
    },
    {
      "day": "2026-09-05",
      "commits": 7,
      "insertions": 184,
      "deletions": 119,
      "byType": {
        "design": 7
      },
      "headline": "One grid language across the whole product",
      "body": "A short, single-purpose pass: the board card grid, the route stop grid and the driver summary metrics are all rebuilt on the same ruled logic, the shared card radius comes down, and over-limit driver details get their own flag. Route details and stop status end the day speaking one visual language instead of three.",
      "decisions": 114,
      "shots": [
        {
          "view": "shift-board",
          "at": "2026-09-05T11:53",
          "src": "/progress/2026-09-05-1153-shift-board.jpg"
        },
        {
          "view": "route-file",
          "at": "2026-09-05T11:53",
          "src": "/progress/2026-09-05-1153-route-file.jpg"
        },
        {
          "view": "lookout-timeline",
          "at": "2026-09-05T11:53",
          "src": "/progress/2026-09-05-1153-lookout-timeline.jpg"
        }
      ]
    },
    {
      "day": "2026-09-06",
      "commits": 41,
      "insertions": 1346,
      "deletions": 657,
      "byType": {
        "design": 17,
        "feat": 4,
        "fix": 2,
        "style": 5,
        "other": 12,
        "docs": 1
      },
      "headline": "The long polish — and the map learns to answer back",
      "body": "The heaviest day by far. It opens on the fleet map becoming interactive: picking a driver draws their whole route. Then a sustained visual pass — route rail and stop numbering, alerts separated from the driver summary, stop cards connected by a timeline spine, board cards keylined by limit status, route details aligned to the board palette. Lookout gets a crisp pixel face and a monospaced voice. Late in the day the route timeline is reversed to lead with remaining work rather than history, stop selection moves beside the actions, and receipts are re-cut to read pick-then-act. Board and Map become one segmented control, and a route file remembers where it was opened from.",
      "decisions": 151,
      "shots": [
        {
          "view": "shift-board",
          "at": "2026-09-06T23:12",
          "src": "/progress/2026-09-06-2312-shift-board.jpg"
        },
        {
          "view": "route-file",
          "at": "2026-09-06T23:12",
          "src": "/progress/2026-09-06-2312-route-file.jpg"
        },
        {
          "view": "fleet-map",
          "at": "2026-09-06T23:12",
          "src": "/progress/2026-09-06-2312-fleet-map.jpg"
        },
        {
          "view": "lookout-timeline",
          "at": "2026-09-06T23:12",
          "src": "/progress/2026-09-06-2312-lookout-timeline.jpg"
        }
      ]
    },
    {
      "day": "2026-09-07",
      "commits": 24,
      "insertions": 621,
      "deletions": 259,
      "byType": {
        "other": 20,
        "feat": 2,
        "design": 1,
        "docs": 1
      },
      "headline": "Lookout keeps receipts; the shift runs on the real clock",
      "body": "Lookout's recommendations are summarized as actions, its alert borders take colour by severity, and an Artifacts tab replaces the Timeline with a reserved empty state. The product navigation flattens, and the simulated shift starts playing against the real clock rather than a frozen anchor. Late on, the fleet map grows a driver list beside it with the zoom moved clear to the bottom right, stop receipts lead their identity column with a status chip, and Lookout's recommendation wash is retuned. The night runs long on the route workspace: route cards animate into their detail view, route status moves into a Stops bar that spans the pane, and the stop receipts get real interaction states.",
      "decisions": 172,
      "shots": [
        {
          "view": "shift-board",
          "at": "2026-09-07T22:05",
          "src": "/progress/2026-09-07-2205-shift-board.jpg"
        },
        {
          "view": "route-file",
          "at": "2026-09-07T22:05",
          "src": "/progress/2026-09-07-2205-route-file.jpg"
        },
        {
          "view": "fleet-map",
          "at": "2026-09-07T22:05",
          "src": "/progress/2026-09-07-2205-fleet-map.jpg"
        },
        {
          "view": "lookout-artifacts",
          "at": "2026-09-07T22:05",
          "src": "/progress/2026-09-07-2205-lookout-artifacts.jpg"
        }
      ]
    },
    {
      "day": "2026-09-08",
      "commits": 67,
      "insertions": 3245,
      "deletions": 990,
      "byType": {
        "other": 19,
        "ops": 1,
        "feat": 14,
        "docs": 1,
        "fix": 4,
        "style": 27,
        "copy": 1
      },
      "headline": "It ships, it gets a name, and it learns to explain itself",
      "body": "The build goes public: deployed to Vercel with the live link in the README. Then three things arrive that were never in the brief. A Metrics lens turns the board into a chart surface with sections, a chooser and a limit forecast. Lena's avatar in the product bar opens a settings page that walks Project, Lena, Problems, Solutions, Why — the case for the work, inside the work. And the product takes an identity: a Dispatch logistics mark, then the Sora Fleet Echo brand applied across the chrome. Underneath, motion tokens land and Lookout learns to slide rather than snap.",
      "decisions": 219,
      "shots": [
        {
          "view": "shift-board",
          "at": "2026-09-08T18:12",
          "src": "/progress/2026-09-08-1812-shift-board.jpg"
        },
        {
          "view": "route-file",
          "at": "2026-09-08T18:12",
          "src": "/progress/2026-09-08-1812-route-file.jpg"
        },
        {
          "view": "fleet-map",
          "at": "2026-09-08T18:12",
          "src": "/progress/2026-09-08-1812-fleet-map.jpg"
        },
        {
          "view": "lookout-artifacts",
          "at": "2026-09-08T18:12",
          "src": "/progress/2026-09-08-1812-lookout-artifacts.jpg"
        }
      ]
    },
    {
      "day": "2026-09-09",
      "commits": 17,
      "insertions": 1350,
      "deletions": 205,
      "byType": {
        "style": 12,
        "other": 2,
        "feat": 3
      },
      "headline": "The last pass is all restraint",
      "body": "Almost nothing is added; things are taken away or settled down. Drop shadows leave the board's controls, the Filters menu's headings drop to plain groups, the Metrics lens collapses to one header row, and the route file's content column caps at 64rem so it stops sprawling on wide screens. What does get added is explanation: Lookout introduces itself when Lena clicks its name, and its pick chip opens a dialog on how it orders the shift. Late in the day Lookout gains an Activity tab — the shift's own record — and every shift event starts remembering what Lena did and what was true when she did it.",
      "decisions": 240,
      "shots": [
        {
          "view": "shift-board",
          "at": "2026-09-09T16:24",
          "src": "/progress/2026-09-09-1624-shift-board.jpg"
        },
        {
          "view": "route-file",
          "at": "2026-09-09T16:24",
          "src": "/progress/2026-09-09-1624-route-file.jpg"
        },
        {
          "view": "lookout-activity",
          "at": "2026-09-09T16:24",
          "src": "/progress/2026-09-09-1624-lookout-activity.jpg"
        },
        {
          "view": "fleet-map",
          "at": "2026-09-09T16:24",
          "src": "/progress/2026-09-09-1624-fleet-map.jpg"
        }
      ]
    }
  ],
  "milestones": [
    {
      "at": "2026-09-03T17:06",
      "hash": "db6168f",
      "title": "Design docs before a line of code",
      "body": "The brief, layout, flows, architecture spec and decision log land first. The app is designed on paper for an hour before the scaffold exists."
    },
    {
      "at": "2026-09-03T18:36",
      "hash": "78591da",
      "title": "A running board ninety minutes after the scaffold",
      "body": "Seeded fleet, pure HOS math with tests, rules as data, the three-pane shell, Lookout, the route file — and the generated fleet moving against the clock."
    },
    {
      "at": "2026-09-04T13:23",
      "hash": "af71be0",
      "title": "A second tool signs the log",
      "body": "Codex takes its first design pass across the board, cards, route rail and Lookout. From here the build is two tools working the same tree."
    },
    {
      "at": "2026-09-04T17:05",
      "hash": "978a691",
      "title": "The map ships",
      "body": "A map view on the route file with the truck as a live fix — the Phase 2 feature the brief said never to put on the critical path, kept behind a toggle."
    },
    {
      "at": "2026-09-06T22:29",
      "hash": "24a2638",
      "title": "Board and Map become one control",
      "body": "One segmented switch, and a route file that remembers where it was opened from. The product stops being two pages and becomes one workspace."
    },
    {
      "at": "2026-09-08T09:02",
      "hash": "2da6859",
      "title": "Live on Vercel",
      "body": "Deployed with the Vite preset, the live link in the README. From this commit on, every change is public within a minute."
    },
    {
      "at": "2026-09-08T15:05",
      "hash": "147dcce",
      "title": "The project file",
      "body": "Lena's avatar opens a settings page that walks Project, Lena, Problems, Solutions, Why — the case for the work, made inside the work."
    },
    {
      "at": "2026-09-09T14:14",
      "hash": "40ad763",
      "title": "Lookout explains itself",
      "body": "Its pick chip opens a dialog on how it orders the shift. The co-pilot's last feature is accountability for its own ranking."
    }
  ],
  "remote": "https://github.com/davekeller/dispatcher-dashboard"
}
